### PR TITLE
Update arrays.xml

### PR DESCRIPTION
**Pull request by michalos1**
greek language

### CODE REVIEW

**Comment by BurgerZ** [comment]
Oh NO!
You should not touch default ENGLISH folder! 
If you want greek translation you should create the GREEK values folder instead.

**Comment by michalos1** [comment]
Soory for that !
I tried but i could find how to create new folder!

**Comment by BurgerZ** [comment]
Give me your translation so I could push it to my repo. Also I can add you as repo collaborator (possibility to edit my repo directly)

**Comment by michalos1** [comment]
Please create a folder with the name values-el in WeatherBZ/res/ and put arays.xml and strigs.xml files inside and i will translate them

**Comment by BurgerZ** [comment]
Done. I have added default xmls (english).
Now you can edit your language directly in my repo.

**Comment by michalos1** [comment]
I did copy-paste the xlms files and i edit them with notepad++ and i did again copy paste to values-el directory
Is ready the translation i think ,the only think i left in english are tha names of the countries
i will translate them also another day
Please if is right the files put greek language in next update of the program
thanks

**Comment by BurgerZ** [comment]
OK. Next update will include your translation, thanks!

**Pull request closed without merging**
